---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "vppagent-client"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "vppagent-client"
    spec:
      hostPID: true
      containers:
        - name: vppagent-client
          image: networkservicemesh/vpp-icmp-vppagent-client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_NETWORK_SERVICE
              value: "icmp-responder"
            - name: CLIENT_LABELS
              value: "app=vppagent-client"
            - name: TRACER_ENABLED
              value: "true"
            - name: JAEGER_SERVICE_HOST
              value: jaeger.nsm-system
            - name: JAEGER_SERVICE_PORT_JAEGER
              value: "6831"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-client
