apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "vl3-client2"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "vl3-client2"
    spec:
      containers:
        - name: kiali
          image: tiswanso/kali_testssl:latest
          command: ["/bin/sleep","infinity"]
          imagePullPolicy: IfNotPresent
metadata:
  name: "vl3-client2"
  namespace: default
  annotations:
    ns.networkservicemesh.io: vl3-service
