---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "pcrf"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "pcrf"
    spec:
      containers:
        - name: pcrf
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
metadata:
  name: "pcrf"
  namespace: default
  annotations:
    ns.networkservicemesh.io: 4g-network?app=gx
