---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "s-gw-c"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "s-gw-c"
    spec:
      containers:
        - name: s-gw-c
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
metadata:
  name: "s-gw-c"
  namespace: default
  annotations:
    ns.networkservicemesh.io: 4g-network?app=s11,4g-network?app=s5s8-c,4g-network?app=sxa
