---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "tdf-u"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "tdf-u"
        networkservicemesh.io/impl: "4g-network"
    spec:
      containers:
        - name: sidecar-nse
          image: networkservicemesh/proxy-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ADVERTISE_NSE_NAME
              value: "4g-network"
            - name: ADVERTISE_NSE_LABELS
              value: "app=tdf-u"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.4.0/30"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: alpine
          image: alpine:latest
          imagePullPolicy: IfNotPresent
metadata:
  name: tdf-u
  namespace: default
