---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "bridge-domain-ipv6"
      networkservicemesh.io/impl: "bridge-ipv6"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "bridge-domain-ipv6"
        networkservicemesh.io/impl: "bridge-ipv6"
    spec:
      serviceAccount: nse-acc
      containers:
        - name: bridge-domain
          image: networkservicemesh/bridge-domain-bridge:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "bridge-domain-ipv6"
            - name: ENDPOINT_LABELS
              value: "app=bridge-ipv6"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "1200::/120"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: bridge-domain-ipv6
  namespace: default
