---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "simple-client"
  replicas: 3
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "simple-client"
    spec:
      # Enable this with INSECURE=false
      # serviceAccount: nsc-acc
      containers:
        - name: alpine-img
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]
metadata:
  name: simple-client
  namespace: default
  annotations:
    ns.networkservicemesh.io: bridge-domain?app=bridge
